### ISSUE TITLE
Improve accessibility of the "read more" links

### ISSUE THREAD

**Issue by michaelhastrich** [fronteers/website#165]
Currently a lot of cards have a "Read more" or "Meld je aan" which is not very accessible. The idea of this issue is to improve on this. Suggestion is to make the title of a card the label for the link. This will probably need some refactoring of the HTML of the cards.

**Comment by SleeplessByte** [comment]
My suggestion would to keep the read more button because it helps for people who browse the site visually. It _is_ a good idea to make the title a link, because a screen reader will read the linked title, appended by `link`, which is a much better link than the context-require `"Read More"`. In that case, mark the `Read More` button as `aria-hidden="true"`.
