### ISSUE TITLE
Language toggle should keep the page subject

### ISSUE THREAD

**Issue by edwinm** [fronteers/website#249]
## Description
When on a subpage and clicking the nl/en toggle, the user should go to the other language, but still on the same subject. For example, when on the Dutch "Activiteiten" page, and the user clicks "en", the user should go to the "Activities" page, not the English root of the site.

Also add link rel="alternate"

## Why should we include this?
To make switching languages easier

## Happy flow
Go to the Dutch "Activiteiten" page. Click EN. Now the user should be on the "Activities" page.

See #183

**Comment by Schepp** [comment]
As this is a hard to solve problem with our overall site structure, especially when tags are involved, we, as in the bestuur, agreed on simplifying the switcher to always point to the home page, as otherwise this holds us back from launching. Being sent to the main page seemed an acceptable compromise between bugfreeness/maintainability and desired functionality.
