### ISSUE TITLE
UX improvement 'upcoming events'

### ISSUE THREAD

**Issue by anneke** [fronteers/website#254]
## Description
On the first few events...
![Scherm­afbeelding 2023-06-24 om 16 45 04](https://github.com/fronteers/website/assets/7202272/a9059cfd-e229-4ac9-81ab-0ecbaa9b180e)

if the event has a date in the past, clarify that it is a past event.
Possibly do the same for other items with a date (vacancies).

**Comment by anneke** [comment]
Let's change "Binnenkort" to "Agenda" and come up with a visual way to show a difference between an event that has been and an event that will still take place (like: the sign up button only shows on events in the future)

**Comment by Mangamaui** [comment]
@anneke wasn't this issue already picked up and done by someone?

**Comment by michaelhastrich** [comment]
Isn't it strange to show passed events here at all?! I understand we want an archive for passed events, but I don't feel there is a need to keep showing them in this overview. I feel it would be better to make a design for 1, 2 and max 3 upcoming events (since we probably don't have a whole series of events lined up) and then also have an archive page for events that already took place.

**Comment by Mangamaui** [comment]
@michaelhastrich thanks for your input, that makes sense indeed. :)

As it happens, I did something similar in one of my own projects:
https://events.womendotcode.be/events/. (note that the homepage is not working atm)

**Comment by michaelhastrich** [comment]
Exactly… that makes much more sense and also prevents having to come up with all sorts of ideas to communicate events in the past
