### ISSUE TITLE
Missing banner/hero on https://www.fronteers.nl/nl/werk-en-freelance/vacature-plaatsen/voorwaarden

### ISSUE THREAD

**Issue by banaan666** [fronteers/website#460]
**Describe the bug**
The page title and banner are missing on both pages (NL and EN)

**To Reproduce**
View:
https://www.fronteers.nl/nl/werk-en-freelance/vacature-plaatsen/voorwaarden
https://www.fronteers.nl/en/jobs/post-job-opening/toc

**Expected behavior**
Banner/hero showing with page title at top of the page

**Comment by banaan666** [comment]
I tried to understand what is causing this so I could fix it myself. But no luck so far. I hope somebody can tell me what to do so I can learn something and fix it myself.

**Comment by SleeplessByte** [comment]
@banaan666 is this your goal?

![image](https://github.com/user-attachments/assets/1117cdaa-dc5e-4c6e-8c30-2ae2f442ce20)

**Comment by banaan666** [comment]
Yepp something like that.

**Comment by SleeplessByte** [comment]
Files inside any folder will look for `<exact-match>.json` for the file configuration, or `<exact-match-folder>.json` or then for any folder above it. So for example `/en/jobs/post-job-opening/toc.md` checks in order:

1. `/en/jobs/post-job-opening/toc.json` ❌
2. `/en/jobs/post-job-opening/post-job-opening.json` ❌
3. `/en/jobs/jobs.json` ✅

In this file we see:

```json
{
  "layout": "jobs-single.liquid",
  "tags": "jobs",
  "useHero": "aboutushero",
  "shield": "jobs"
}
```

The layout it will use is `jobs-single.liquid` and the hero is set up, but for some reason not shown.

| `jobs-single.liquid` | `page.liquid` |
|----------------------|---------------|
| does not show hero   | shows hero    |

Comparing the file gives the answer:

```liquid
{%# jobs-single.liquid %}
{%- include partials/utility/html-head -%}
<body data-layout="jobs-single">
    {%- include partials/page-header/_page-header -%}

    <main id="main" class="page-content inner-wrapper">
        {% unless useHero %}
            <h2>{{ title }}</h2>
        {% endunless %}
        {{ content }}
    </main>

    {%- include partials/utility/edit-this-page -%}

    {%- include partials/page-footer/_page-footer -%}
</body>
</html>

```

```liquid
{%# page.liquid %}
{%- include partials/utility/html-head -%}
<body data-layout="jobs-single">
    {%- include partials/page-header/_page-header -%}

    <main id="main" class="{% if useHero %}styledheader{% endif %}">
        {% if useHero == 'aboutushero' %}
            {%- aboutushero title shield -%}
                {{ heroSlogan }}
            {%- endaboutushero -%}
        {% endif %}

        <div class="page-content inner-wrapper">
            {% unless useHero %}
                <h2>{{ title }}</h2>
            {% endunless %}

            {{ content }}
        </div>
    </main>

    {%- include partials/utility/edit-this-page -%}

    {%- include partials/page-footer/_page-footer -%}
</body>
</html>
```

In order to make the hero work, you want it to use the page layout instead. But because we may want to make changes to the layout of the `jobs` pages, you can decide to keep the separate template. In this case, replace the contents with the `page.liquid` file, and update `data-layout` to `jobs-single` so we can find it (inspect source, so you know what was rendered).

Then, update the `frontmatter` of the page:

```markdown
---
title: Vacature plaatsen
excludeFromCollection: true
key: terms-and-conditions-jobs
heroSlogan: "Voorwaarden"
---

[...]
```

`heroSlogan` is shown underneath `title`.

Finally, you don't need to worry about the `shield` graphic. Because it is fixed to the [generated result of the string `jobs`](https://codesandbox.io/p/sandbox/fronteers-shield-generator-8xrp4y), so it will look the same for all the "vacature" related pages!
